{
 "title": "System Metrics for the Linux Hosts",
 "description": "Monitoring Linux Hosts via telegraf agent.",
 "tags": [
  "prometheus",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(system_uptime, instance)"
   },
   {
    "name": "disk_device",
    "query": "label_values(disk_used_percent{fstype!=\"rootfs\", instance=\"$instance\"}, device)"
   },
   {
    "name": "interface",
    "query": "label_values(net_bytes_sent{instance=\"$instance\"}, interface)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_n_cpus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Logged In Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_n_users{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{instance=\"$instance\",interface!~\"lo\"}[1m])",
     "legendFormat": "received by the {{interface}}"
    },
    {
     "expr": "rate(net_bytes_sent{instance=\"$instance\",interface!~\"lo\"}[1m])",
     "legendFormat": "sent by the {{interface}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "processes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(100-cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"})"
      }
     ]
    },
    {
     "title": "CPU Total %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_user{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "User"
      },
      {
       "expr": "cpu_usage_system{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "System"
      },
      {
       "expr": "cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load1{instance=\"$instance\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "system_load5{instance=\"$instance\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "system_load15{instance=\"$instance\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "processes_blocked{instance=\"$instance\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "processes_dead{instance=\"$instance\"}",
       "legendFormat": "Dead"
      },
      {
       "expr": "processes_idle{instance=\"$instance\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "processes_paging{instance=\"$instance\"}",
       "legendFormat": "Paging"
      },
      {
       "expr": "processes_running{instance=\"$instance\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "processes_sleeping{instance=\"$instance\"}",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "processes_stopped{instance=\"$instance\"}",
       "legendFormat": "Stopped"
      },
      {
       "expr": "processes_unknown{instance=\"$instance\"}",
       "legendFormat": "Unknown"
      },
      {
       "expr": "processes_zombies{instance=\"$instance\"}",
       "legendFormat": "Zombies"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "mem_used_percent{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mem_used{instance=~\"$instance*\"}",
       "legendFormat": "mem_used"
      },
      {
       "expr": "mem_buffered{instance=~\"$instance\"}",
       "legendFormat": "mem_buffered"
      },
      {
       "expr": "mem_cached{instance=~\"$instance\"}",
       "legendFormat": "mem_cached"
      },
      {
       "expr": "swap_used{instance=~\"$instance\"}",
       "legendFormat": "mem_swap"
      },
      {
       "expr": "mem_free{instance=\"$instance\"}",
       "legendFormat": "mem_free"
      }
     ]
    }
   ]
  },
  {
   "title": "Block devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks Usages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "disk_used_percent{instance=~\"$instance\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{instance=~\"$instance\",name!~\"dm-[0-9]\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk IO Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_write_bytes{instance=~\"$instance\",name!~\"dm-[0-9]\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}